name: build on change

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
  repository_dispatch:
    types: webssh

jobs:

  compare:
    runs-on: ubuntu-latest
    outputs:
      flag: ${{ steps.set-flag.outputs.flag }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm, arm64]
    steps:
      - name: checkoutrepository
        uses: actions/checkout@v2
      - name: container registries
        run: |
          docker login docker.io -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: compare image
        id: set-flag
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          version="latest"
          repo="treehouses/webssh-tags:${{ matrix.arch }}"
          case ${{ matrix.arch }} in
            amd64) : "treehouses/alpine:$version" ;;
            arm) : "treehouses/alpine:$version" ;;
            arm64) : "treehouses/alpine:$version" ;;
          esac
          base="$_"
          docker pull -q $base &>/dev/null
          docker pull -q $repo &>/dev/null
          basesha=$(docker image inspect $base | jq --raw-output '.[0].RootFS.Layers|.[]')
          reposha=$(docker image inspect $repo | jq --raw-output '.[0].RootFS.Layers|.[]')
          echo "base sha:$basesha repo sha:$reposha"
          [[ $reposha == *$basesha* ]] && echo "no changes" || echo "::set-output name=flag::true"

  images:
    needs: compare
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.set-build.outputs.build }}
        strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm, arm64]
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: container registries
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker login docker.io -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: docker image
        if: ${{ needs.compare.outputs.flag }}
        id: set-build
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          version="version"
          case ${{ matrix.arch }} in
            amd64) : "treehouses/alpine:$version" ;;
            arm) : "treehouses/alpine:$version" ;;
            arm64) : "treehouses/alpine:$version" ;;
          esac
          image="$_"
          repo="treehouses/alpine-tags"
          dest="$repo:${{ matrix.arch }}"
          date="$(date +%Y%m%d%H%M)"
          echo "::set-output name=build::true"
          
          
          
          
          
          # docker build -t ghcr.io/$dest --build-arg IMAGE=$image . 
          # docker tag ghcr.io/$dest docker.io/$dest
          # docker tag ghcr.io/$dest ghcr.io/$dest-$date
          # docker tag docker.io/$dest docker.io/$dest-$date
          # docker push --all-tags ghcr.io/$repo
          # docker push --all-tags docker.io/$repo
          # docker images
          # echo "::set-output name=build::true"