name: build on change

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
  repository_dispatch:
    types: webssh

jobs:

  compare:
    runs-on: ubuntu-latest
    outputs:
      flag: ${{ steps.set-flag.outputs.flag }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm, arm64]
    steps:
      - name: checkoutrepository
        uses: actions/checkout@v2
      - name: container registries
        run: |
          docker login docker.io -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: compare image
        id: set-flag
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          version="latest"
          repo="treehouses/webssh-tags:${{ matrix.arch }}"
          case ${{ matrix.arch }} in
            amd64) : "treehouses/alpine:$version" ;;
            arm) : "treehouses/alpine:$version" ;;
            arm64) : "treehouses/alpine:$version" ;;
          esac
          base="$_"
          docker pull -q $base &>/dev/null
          docker pull -q $repo &>/dev/null
          basesha=$(docker image inspect $base | jq --raw-output '.[0].RootFS.Layers|.[]')
          reposha=$(docker image inspect $repo | jq --raw-output '.[0].RootFS.Layers|.[]')
          echo "base sha:$basesha repo sha:$reposha"
          [[ $reposha == *$basesha* ]] && echo "no changes" || echo "::set-output name=flag::true"
  images:
    needs: compare
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.set-build.outputs.build }}
        strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm, arm64]
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: container registries
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker login docker.io -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
